Vol 1. up for review
Shuckdub/Distraction-Shield pull request #1
Opened 2020-03-17 23:35 UTC by Shuckdub

2020-03-23 23:02 UTC, mircealungu commented on src/components/options/ExerciseOptions.js
> +        let exerciseDuration = defaultexerciseDuration;
why not use the exercise duration from storage anymore?

2020-03-24 00:02 UTC, mircealungu requested changes

2020-03-24 00:02 UTC, mircealungu commented on src/components/options/Statistics.js
> +                    {"name":"b.dk", "value":3},
hmm. what's this?

2020-03-24 00:02 UTC, mircealungu commented on src/pages/Intercepted.js
> +            //if (timeLeft <= 0) clearInterval(this.state.timer)
why leave commented lines of code in? 
if it's not necessary, remove it.

2020-03-24 00:02 UTC, mircealungu commented on src/pages/Intercepted.js
> +        setHistoricalFirebase('Succes');
i've seen this function a lot of times, and I still don't 
understand what it does. what is the meaning of "set historical firebase"?
can you rename it in a more intention-revealing way?

2020-03-24 00:02 UTC, mircealungu commented on src/util/fire.js
> +import firebase from 'firebase';
why not name the file firebase.js? you're not saving that much with calling it "fire"

2020-08-20 15:24 UTC, mircealungu commented
@Shuckdub - any progress on answering my feedback?
then we can eventually merge the PR!

2020-08-27 12:32 UTC, closed without merging

2020-08-27 12:33 UTC, Shuckdub commented
This pull is not valid. I will make another pull from the final code.